[ClassVersion("1.0.0"), FriendlyName("ROWBuildingBlock")]
class VE_ROWBuildingBlock : OMI_BaseResource
{
    [Key, Description("RES ONE Workspace building block file path")] String Path;
    [Write, Description("RES ONE Workspace user credential"), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Overwrite existing objects in the RES ONE Workspace database")] Boolean Overwrite;
    [Write, Description("Remove objects in the building block from the RES ONE Workspace database")] Boolean Delete;
    [Write, Description("Delete the source building block file after import")] Boolean DeleteFromDisk;
};
